### ISSUE TITLE
PDF typo page 67

### ISSUE THREAD

**Issue by i336** [xoreaxeaxeax/sinkhole#4]
"Exectuion"

Not sure if the PDF is final, thought I'd say something in case fixes are still relevant.

(Oh, also, since I have a comm channel open: is there/will there be (?) a video of this anywhere?)

**Comment by xoreaxeaxeax** [comment]
Fixed, thanks!
The Black Hat videos usually aren't officially openly released online, but typically make their way to YouTube at some point.

**Comment by i336** [comment]
Thanks for the response :P  
I'll be sure to look out for a YouTube copy of this sometime. I might even be able to understand some of the concepts! XD

**Comment by NateBrune** [comment]
I tried to explain what this vulnerability is/does [on reddit](https://www.reddit.com/r/linux/comments/3g97dc/the_memory_sinkhole_an_x86_design_flaw_allowing/ctxkwyf)  a couple of days ago if you wanted to get an idea

**Comment by i336** [comment]
Cool. I had a look, and it explained and clarified a few bits I hadn't grasped, thanks!
